#############################################################################
# Makefile for building: ConflictResolver
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?r. lis 24 15:07:39 2010
# Project:  ConflictResolver.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile ConflictResolver.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_TESTLIB_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtTest -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtTest -lQtXmlPatterns -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		contentmanagerwindow.cpp \
		conflictresolverwindow.cpp \
		filesset.cpp \
		filessetdelegate.cpp \
		contentmodel.cpp \
		contentrecord.cpp \
		tmrecord.cpp \
		filtersdialog.cpp \
		fuzzystrings.cpp \
		editdialog.cpp \
		contentdelegate.cpp \
		inifile.cpp \
		tmheader.cpp \
		saver.cpp \
		tmsaver.cpp \
		glossaryextractordialog.cpp \
		fuzzyoptionsdialog.cpp \
		glossaryfile.cpp \
		tmfile.cpp \
		filemerger.cpp \
		conflictscontainer.cpp \
		conflictrecord.cpp \
		tests/filemergertests.cpp \
		tests/glossaryfiletests.cpp \
		tmxfile.cpp \
		tmxrecord.cpp \
		tests/tmfiletests.cpp \
		owngui/contentwidget.cpp \
		owngui/conflictswidget.cpp \
		commons/error.cpp \
		commons/errormanager.cpp \
		owngui/multiplecontentwidget.cpp moc_mainwindow.cpp \
		moc_contentmanagerwindow.cpp \
		moc_conflictresolverwindow.cpp \
		moc_filesset.cpp \
		moc_filessetdelegate.cpp \
		moc_contentmodel.cpp \
		moc_contentrecord.cpp \
		moc_tmrecord.cpp \
		moc_filtersdialog.cpp \
		moc_fuzzystrings.cpp \
		moc_editdialog.cpp \
		moc_contentdelegate.cpp \
		moc_inifile.cpp \
		moc_tmheader.cpp \
		moc_saver.cpp \
		moc_tmsaver.cpp \
		moc_glossaryextractordialog.cpp \
		moc_fuzzyoptionsdialog.cpp \
		moc_glossaryfile.cpp \
		moc_tmfile.cpp \
		moc_filemerger.cpp \
		moc_conflictscontainer.cpp \
		moc_conflictrecord.cpp \
		moc_filemergertests.cpp \
		moc_glossaryfiletests.cpp \
		moc_tmxfile.cpp \
		moc_tmxrecord.cpp \
		moc_tmfiletests.cpp \
		moc_contentwidget.cpp \
		moc_conflictswidget.cpp \
		moc_error.cpp \
		moc_errormanager.cpp \
		moc_multiplecontentwidget.cpp
OBJECTS       = main.o \
		mainwindow.o \
		contentmanagerwindow.o \
		conflictresolverwindow.o \
		filesset.o \
		filessetdelegate.o \
		contentmodel.o \
		contentrecord.o \
		tmrecord.o \
		filtersdialog.o \
		fuzzystrings.o \
		editdialog.o \
		contentdelegate.o \
		inifile.o \
		tmheader.o \
		saver.o \
		tmsaver.o \
		glossaryextractordialog.o \
		fuzzyoptionsdialog.o \
		glossaryfile.o \
		tmfile.o \
		filemerger.o \
		conflictscontainer.o \
		conflictrecord.o \
		filemergertests.o \
		glossaryfiletests.o \
		tmxfile.o \
		tmxrecord.o \
		tmfiletests.o \
		contentwidget.o \
		conflictswidget.o \
		error.o \
		errormanager.o \
		multiplecontentwidget.o \
		moc_mainwindow.o \
		moc_contentmanagerwindow.o \
		moc_conflictresolverwindow.o \
		moc_filesset.o \
		moc_filessetdelegate.o \
		moc_contentmodel.o \
		moc_contentrecord.o \
		moc_tmrecord.o \
		moc_filtersdialog.o \
		moc_fuzzystrings.o \
		moc_editdialog.o \
		moc_contentdelegate.o \
		moc_inifile.o \
		moc_tmheader.o \
		moc_saver.o \
		moc_tmsaver.o \
		moc_glossaryextractordialog.o \
		moc_fuzzyoptionsdialog.o \
		moc_glossaryfile.o \
		moc_tmfile.o \
		moc_filemerger.o \
		moc_conflictscontainer.o \
		moc_conflictrecord.o \
		moc_filemergertests.o \
		moc_glossaryfiletests.o \
		moc_tmxfile.o \
		moc_tmxrecord.o \
		moc_tmfiletests.o \
		moc_contentwidget.o \
		moc_conflictswidget.o \
		moc_error.o \
		moc_errormanager.o \
		moc_multiplecontentwidget.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ConflictResolver.pro
QMAKE_TARGET  = ConflictResolver
DESTDIR       = 
TARGET        = ConflictResolver

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_contentmanagerwindow.h ui_conflictresolverwindow.h ui_filtersdialog.h ui_editdialog.h ui_glossaryextractordialog.h ui_fuzzyoptionsdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ConflictResolver.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtTest.prl \
		/usr/lib/libQtXmlPatterns.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile ConflictResolver.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtTest.prl:
/usr/lib/libQtXmlPatterns.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile ConflictResolver.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ConflictResolver1.0.0 || $(MKDIR) .tmp/ConflictResolver1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ConflictResolver1.0.0/ && $(COPY_FILE) --parents mainwindow.h contentmanagerwindow.h conflictresolverwindow.h filesset.h filessetdelegate.h contentmodel.h contentrecord.h tmrecord.h filtersdialog.h fuzzystrings.h editdialog.h contentdelegate.h inifile.h tmheader.h saver.h tmsaver.h glossaryextractordialog.h fuzzyoptionsdialog.h glossaryfile.h tmfile.h filemerger.h conflictscontainer.h conflictrecord.h tests/filemergertests.h tests/glossaryfiletests.h tests/Tests.h tmxfile.h tmxrecord.h tests/tmfiletests.h owngui/contentwidget.h owngui/conflictswidget.h commons/error.h commons/errormanager.h owngui/multiplecontentwidget.h .tmp/ConflictResolver1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp contentmanagerwindow.cpp conflictresolverwindow.cpp filesset.cpp filessetdelegate.cpp contentmodel.cpp contentrecord.cpp tmrecord.cpp filtersdialog.cpp fuzzystrings.cpp editdialog.cpp contentdelegate.cpp inifile.cpp tmheader.cpp saver.cpp tmsaver.cpp glossaryextractordialog.cpp fuzzyoptionsdialog.cpp glossaryfile.cpp tmfile.cpp filemerger.cpp conflictscontainer.cpp conflictrecord.cpp tests/filemergertests.cpp tests/glossaryfiletests.cpp tmxfile.cpp tmxrecord.cpp tests/tmfiletests.cpp owngui/contentwidget.cpp owngui/conflictswidget.cpp commons/error.cpp commons/errormanager.cpp owngui/multiplecontentwidget.cpp .tmp/ConflictResolver1.0.0/ && $(COPY_FILE) --parents mainwindow.ui contentmanagerwindow.ui conflictresolverwindow.ui filtersdialog.ui editdialog.ui glossaryextractordialog.ui fuzzyoptionsdialog.ui .tmp/ConflictResolver1.0.0/ && (cd `dirname .tmp/ConflictResolver1.0.0` && $(TAR) ConflictResolver1.0.0.tar ConflictResolver1.0.0 && $(COMPRESS) ConflictResolver1.0.0.tar) && $(MOVE) `dirname .tmp/ConflictResolver1.0.0`/ConflictResolver1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ConflictResolver1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_contentmanagerwindow.cpp moc_conflictresolverwindow.cpp moc_filesset.cpp moc_filessetdelegate.cpp moc_contentmodel.cpp moc_contentrecord.cpp moc_tmrecord.cpp moc_filtersdialog.cpp moc_fuzzystrings.cpp moc_editdialog.cpp moc_contentdelegate.cpp moc_inifile.cpp moc_tmheader.cpp moc_saver.cpp moc_tmsaver.cpp moc_glossaryextractordialog.cpp moc_fuzzyoptionsdialog.cpp moc_glossaryfile.cpp moc_tmfile.cpp moc_filemerger.cpp moc_conflictscontainer.cpp moc_conflictrecord.cpp moc_filemergertests.cpp moc_glossaryfiletests.cpp moc_tmxfile.cpp moc_tmxrecord.cpp moc_tmfiletests.cpp moc_contentwidget.cpp moc_conflictswidget.cpp moc_error.cpp moc_errormanager.cpp moc_multiplecontentwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_contentmanagerwindow.cpp moc_conflictresolverwindow.cpp moc_filesset.cpp moc_filessetdelegate.cpp moc_contentmodel.cpp moc_contentrecord.cpp moc_tmrecord.cpp moc_filtersdialog.cpp moc_fuzzystrings.cpp moc_editdialog.cpp moc_contentdelegate.cpp moc_inifile.cpp moc_tmheader.cpp moc_saver.cpp moc_tmsaver.cpp moc_glossaryextractordialog.cpp moc_fuzzyoptionsdialog.cpp moc_glossaryfile.cpp moc_tmfile.cpp moc_filemerger.cpp moc_conflictscontainer.cpp moc_conflictrecord.cpp moc_filemergertests.cpp moc_glossaryfiletests.cpp moc_tmxfile.cpp moc_tmxrecord.cpp moc_tmfiletests.cpp moc_contentwidget.cpp moc_conflictswidget.cpp moc_error.cpp moc_errormanager.cpp moc_multiplecontentwidget.cpp
moc_mainwindow.cpp: contentmanagerwindow.h \
		conflictresolverwindow.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		filesset.h \
		filessetdelegate.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_contentmanagerwindow.cpp: conflictresolverwindow.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		contentmanagerwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) contentmanagerwindow.h -o moc_contentmanagerwindow.cpp

moc_conflictresolverwindow.cpp: contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		conflictresolverwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) conflictresolverwindow.h -o moc_conflictresolverwindow.cpp

moc_filesset.cpp: filesset.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) filesset.h -o moc_filesset.cpp

moc_filessetdelegate.cpp: filessetdelegate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) filessetdelegate.h -o moc_filessetdelegate.cpp

moc_contentmodel.cpp: contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		contentmodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) contentmodel.h -o moc_contentmodel.cpp

moc_contentrecord.cpp: fuzzystrings.h \
		contentrecord.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) contentrecord.h -o moc_contentrecord.cpp

moc_tmrecord.cpp: contentrecord.h \
		fuzzystrings.h \
		tmrecord.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tmrecord.h -o moc_tmrecord.cpp

moc_filtersdialog.cpp: contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		filtersdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) filtersdialog.h -o moc_filtersdialog.cpp

moc_fuzzystrings.cpp: fuzzystrings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fuzzystrings.h -o moc_fuzzystrings.cpp

moc_editdialog.cpp: contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		editdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editdialog.h -o moc_editdialog.cpp

moc_contentdelegate.cpp: filessetdelegate.h \
		contentdelegate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) contentdelegate.h -o moc_contentdelegate.cpp

moc_inifile.cpp: inifile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) inifile.h -o moc_inifile.cpp

moc_tmheader.cpp: tmheader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tmheader.h -o moc_tmheader.cpp

moc_saver.cpp: saver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) saver.h -o moc_saver.cpp

moc_tmsaver.cpp: saver.h \
		contentrecord.h \
		fuzzystrings.h \
		tmheader.h \
		tmsaver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tmsaver.h -o moc_tmsaver.cpp

moc_glossaryextractordialog.cpp: fuzzystrings.h \
		contentrecord.h \
		glossaryextractordialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) glossaryextractordialog.h -o moc_glossaryextractordialog.cpp

moc_fuzzyoptionsdialog.cpp: fuzzyoptionsdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fuzzyoptionsdialog.h -o moc_fuzzyoptionsdialog.cpp

moc_glossaryfile.cpp: fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		glossaryfile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) glossaryfile.h -o moc_glossaryfile.cpp

moc_tmfile.cpp: glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tmfile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tmfile.h -o moc_tmfile.cpp

moc_filemerger.cpp: tmfile.h \
		glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		filemerger.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) filemerger.h -o moc_filemerger.cpp

moc_conflictscontainer.cpp: contentrecord.h \
		fuzzystrings.h \
		filemerger.h \
		tmfile.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		conflictscontainer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) conflictscontainer.h -o moc_conflictscontainer.cpp

moc_conflictrecord.cpp: contentrecord.h \
		fuzzystrings.h \
		inifile.h \
		conflictrecord.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) conflictrecord.h -o moc_conflictrecord.cpp

moc_filemergertests.cpp: tests/Tests.h \
		tests/filemergertests.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tests/filemergertests.h -o moc_filemergertests.cpp

moc_glossaryfiletests.cpp: tests/Tests.h \
		glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tests/glossaryfiletests.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tests/glossaryfiletests.h -o moc_glossaryfiletests.cpp

moc_tmxfile.cpp: glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tmxrecord.h \
		tmrecord.h \
		tmxfile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tmxfile.h -o moc_tmxfile.cpp

moc_tmxrecord.cpp: tmrecord.h \
		contentrecord.h \
		fuzzystrings.h \
		tmxrecord.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tmxrecord.h -o moc_tmxrecord.cpp

moc_tmfiletests.cpp: tmfile.h \
		glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tests/Tests.h \
		tests/tmfiletests.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tests/tmfiletests.h -o moc_tmfiletests.cpp

moc_contentwidget.cpp: conflictrecord.h \
		contentrecord.h \
		fuzzystrings.h \
		inifile.h \
		owngui/contentwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) owngui/contentwidget.h -o moc_contentwidget.cpp

moc_conflictswidget.cpp: owngui/multiplecontentwidget.h \
		conflictrecord.h \
		contentrecord.h \
		fuzzystrings.h \
		inifile.h \
		owngui/conflictswidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) owngui/conflictswidget.h -o moc_conflictswidget.cpp

moc_error.cpp: commons/error.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) commons/error.h -o moc_error.cpp

moc_errormanager.cpp: commons/errormanager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) commons/errormanager.h -o moc_errormanager.cpp

moc_multiplecontentwidget.cpp: conflictrecord.h \
		contentrecord.h \
		fuzzystrings.h \
		inifile.h \
		owngui/multiplecontentwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) owngui/multiplecontentwidget.h -o moc_multiplecontentwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_contentmanagerwindow.h ui_conflictresolverwindow.h ui_filtersdialog.h ui_editdialog.h ui_glossaryextractordialog.h ui_fuzzyoptionsdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_contentmanagerwindow.h ui_conflictresolverwindow.h ui_filtersdialog.h ui_editdialog.h ui_glossaryextractordialog.h ui_fuzzyoptionsdialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_contentmanagerwindow.h: contentmanagerwindow.ui
	/usr/bin/uic-qt4 contentmanagerwindow.ui -o ui_contentmanagerwindow.h

ui_conflictresolverwindow.h: conflictresolverwindow.ui
	/usr/bin/uic-qt4 conflictresolverwindow.ui -o ui_conflictresolverwindow.h

ui_filtersdialog.h: filtersdialog.ui
	/usr/bin/uic-qt4 filtersdialog.ui -o ui_filtersdialog.h

ui_editdialog.h: editdialog.ui
	/usr/bin/uic-qt4 editdialog.ui -o ui_editdialog.h

ui_glossaryextractordialog.h: glossaryextractordialog.ui
	/usr/bin/uic-qt4 glossaryextractordialog.ui -o ui_glossaryextractordialog.h

ui_fuzzyoptionsdialog.h: fuzzyoptionsdialog.ui
	/usr/bin/uic-qt4 fuzzyoptionsdialog.ui -o ui_fuzzyoptionsdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		contentmanagerwindow.h \
		conflictresolverwindow.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		filesset.h \
		filessetdelegate.h \
		tests/Tests.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		contentmanagerwindow.h \
		conflictresolverwindow.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		filesset.h \
		filessetdelegate.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

contentmanagerwindow.o: contentmanagerwindow.cpp contentmanagerwindow.h \
		conflictresolverwindow.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		ui_contentmanagerwindow.h \
		filtersdialog.h \
		glossaryextractordialog.h \
		fuzzyoptionsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contentmanagerwindow.o contentmanagerwindow.cpp

conflictresolverwindow.o: conflictresolverwindow.cpp conflictresolverwindow.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		ui_conflictresolverwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o conflictresolverwindow.o conflictresolverwindow.cpp

filesset.o: filesset.cpp filesset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filesset.o filesset.cpp

filessetdelegate.o: filessetdelegate.cpp mainwindow.h \
		contentmanagerwindow.h \
		conflictresolverwindow.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		filesset.h \
		filessetdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filessetdelegate.o filessetdelegate.cpp

contentmodel.o: contentmodel.cpp contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		tmsaver.h \
		saver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contentmodel.o contentmodel.cpp

contentrecord.o: contentrecord.cpp contentrecord.h \
		fuzzystrings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contentrecord.o contentrecord.cpp

tmrecord.o: tmrecord.cpp tmrecord.h \
		contentrecord.h \
		fuzzystrings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmrecord.o tmrecord.cpp

filtersdialog.o: filtersdialog.cpp filtersdialog.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		ui_filtersdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filtersdialog.o filtersdialog.cpp

fuzzystrings.o: fuzzystrings.cpp fuzzystrings.h \
		inifile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fuzzystrings.o fuzzystrings.cpp

editdialog.o: editdialog.cpp editdialog.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		ui_editdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editdialog.o editdialog.cpp

contentdelegate.o: contentdelegate.cpp contentdelegate.h \
		filessetdelegate.h \
		conflictresolverwindow.h \
		contentmodel.h \
		contentrecord.h \
		fuzzystrings.h \
		tmrecord.h \
		tmheader.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		filemerger.h \
		tmfile.h \
		owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contentdelegate.o contentdelegate.cpp

inifile.o: inifile.cpp inifile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inifile.o inifile.cpp

tmheader.o: tmheader.cpp tmheader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmheader.o tmheader.cpp

saver.o: saver.cpp saver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saver.o saver.cpp

tmsaver.o: tmsaver.cpp tmsaver.h \
		saver.h \
		contentrecord.h \
		fuzzystrings.h \
		tmheader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmsaver.o tmsaver.cpp

glossaryextractordialog.o: glossaryextractordialog.cpp glossaryextractordialog.h \
		fuzzystrings.h \
		contentrecord.h \
		ui_glossaryextractordialog.h \
		inifile.h \
		tmsaver.h \
		saver.h \
		tmheader.h \
		contentmodel.h \
		tmrecord.h \
		glossaryfile.h \
		conflictrecord.h \
		filemerger.h \
		tmfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glossaryextractordialog.o glossaryextractordialog.cpp

fuzzyoptionsdialog.o: fuzzyoptionsdialog.cpp fuzzyoptionsdialog.h \
		ui_fuzzyoptionsdialog.h \
		inifile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fuzzyoptionsdialog.o fuzzyoptionsdialog.cpp

glossaryfile.o: glossaryfile.cpp glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tmsaver.h \
		saver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glossaryfile.o glossaryfile.cpp

tmfile.o: tmfile.cpp tmfile.h \
		glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tmrecord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmfile.o tmfile.cpp

filemerger.o: filemerger.cpp filemerger.h \
		tmfile.h \
		glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tmsaver.h \
		saver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filemerger.o filemerger.cpp

conflictscontainer.o: conflictscontainer.cpp conflictscontainer.h \
		contentrecord.h \
		fuzzystrings.h \
		filemerger.h \
		tmfile.h \
		glossaryfile.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o conflictscontainer.o conflictscontainer.cpp

conflictrecord.o: conflictrecord.cpp conflictrecord.h \
		contentrecord.h \
		fuzzystrings.h \
		inifile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o conflictrecord.o conflictrecord.cpp

filemergertests.o: tests/filemergertests.cpp tests/filemergertests.h \
		tests/Tests.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filemergertests.o tests/filemergertests.cpp

glossaryfiletests.o: tests/glossaryfiletests.cpp tests/glossaryfiletests.h \
		tests/Tests.h \
		glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glossaryfiletests.o tests/glossaryfiletests.cpp

tmxfile.o: tmxfile.cpp tmxfile.h \
		glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tmxrecord.h \
		tmrecord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmxfile.o tmxfile.cpp

tmxrecord.o: tmxrecord.cpp tmxrecord.h \
		tmrecord.h \
		contentrecord.h \
		fuzzystrings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmxrecord.o tmxrecord.cpp

tmfiletests.o: tests/tmfiletests.cpp tests/tmfiletests.h \
		tmfile.h \
		glossaryfile.h \
		fuzzystrings.h \
		contentrecord.h \
		conflictrecord.h \
		inifile.h \
		tmheader.h \
		tests/Tests.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmfiletests.o tests/tmfiletests.cpp

contentwidget.o: owngui/contentwidget.cpp owngui/contentwidget.h \
		conflictrecord.h \
		contentrecord.h \
		fuzzystrings.h \
		inifile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contentwidget.o owngui/contentwidget.cpp

conflictswidget.o: owngui/conflictswidget.cpp owngui/conflictswidget.h \
		owngui/multiplecontentwidget.h \
		conflictrecord.h \
		contentrecord.h \
		fuzzystrings.h \
		inifile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o conflictswidget.o owngui/conflictswidget.cpp

error.o: commons/error.cpp commons/error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o error.o commons/error.cpp

errormanager.o: commons/errormanager.cpp commons/errormanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errormanager.o commons/errormanager.cpp

multiplecontentwidget.o: owngui/multiplecontentwidget.cpp owngui/multiplecontentwidget.h \
		conflictrecord.h \
		contentrecord.h \
		fuzzystrings.h \
		inifile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multiplecontentwidget.o owngui/multiplecontentwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_contentmanagerwindow.o: moc_contentmanagerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contentmanagerwindow.o moc_contentmanagerwindow.cpp

moc_conflictresolverwindow.o: moc_conflictresolverwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_conflictresolverwindow.o moc_conflictresolverwindow.cpp

moc_filesset.o: moc_filesset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filesset.o moc_filesset.cpp

moc_filessetdelegate.o: moc_filessetdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filessetdelegate.o moc_filessetdelegate.cpp

moc_contentmodel.o: moc_contentmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contentmodel.o moc_contentmodel.cpp

moc_contentrecord.o: moc_contentrecord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contentrecord.o moc_contentrecord.cpp

moc_tmrecord.o: moc_tmrecord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tmrecord.o moc_tmrecord.cpp

moc_filtersdialog.o: moc_filtersdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filtersdialog.o moc_filtersdialog.cpp

moc_fuzzystrings.o: moc_fuzzystrings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fuzzystrings.o moc_fuzzystrings.cpp

moc_editdialog.o: moc_editdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editdialog.o moc_editdialog.cpp

moc_contentdelegate.o: moc_contentdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contentdelegate.o moc_contentdelegate.cpp

moc_inifile.o: moc_inifile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inifile.o moc_inifile.cpp

moc_tmheader.o: moc_tmheader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tmheader.o moc_tmheader.cpp

moc_saver.o: moc_saver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_saver.o moc_saver.cpp

moc_tmsaver.o: moc_tmsaver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tmsaver.o moc_tmsaver.cpp

moc_glossaryextractordialog.o: moc_glossaryextractordialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glossaryextractordialog.o moc_glossaryextractordialog.cpp

moc_fuzzyoptionsdialog.o: moc_fuzzyoptionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fuzzyoptionsdialog.o moc_fuzzyoptionsdialog.cpp

moc_glossaryfile.o: moc_glossaryfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glossaryfile.o moc_glossaryfile.cpp

moc_tmfile.o: moc_tmfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tmfile.o moc_tmfile.cpp

moc_filemerger.o: moc_filemerger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filemerger.o moc_filemerger.cpp

moc_conflictscontainer.o: moc_conflictscontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_conflictscontainer.o moc_conflictscontainer.cpp

moc_conflictrecord.o: moc_conflictrecord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_conflictrecord.o moc_conflictrecord.cpp

moc_filemergertests.o: moc_filemergertests.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filemergertests.o moc_filemergertests.cpp

moc_glossaryfiletests.o: moc_glossaryfiletests.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glossaryfiletests.o moc_glossaryfiletests.cpp

moc_tmxfile.o: moc_tmxfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tmxfile.o moc_tmxfile.cpp

moc_tmxrecord.o: moc_tmxrecord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tmxrecord.o moc_tmxrecord.cpp

moc_tmfiletests.o: moc_tmfiletests.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tmfiletests.o moc_tmfiletests.cpp

moc_contentwidget.o: moc_contentwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contentwidget.o moc_contentwidget.cpp

moc_conflictswidget.o: moc_conflictswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_conflictswidget.o moc_conflictswidget.cpp

moc_error.o: moc_error.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_error.o moc_error.cpp

moc_errormanager.o: moc_errormanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_errormanager.o moc_errormanager.cpp

moc_multiplecontentwidget.o: moc_multiplecontentwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_multiplecontentwidget.o moc_multiplecontentwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

